### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by alexbagirov** [sankha93/codejudge#35]
Hello!

How can I compile Java files and use them on a hosting?

**Comment by my-swagger** [comment]
You need to download Java Development Kit first. A quick Google search should point you in the right direction. To compile it's a simple command 'javac MyClass.java' (without quotes) and that will generate a .class file (such as MyClass.class). To run your application just do java MyClass

**Comment by CruiseDevice** [comment]
Were you able to figure out how to run "java -jar codejudge-compiler.jar". I am executing this command but getting this error "Error: Unable to access jarfile codejudge-compiler.jar"
