### ISSUE TITLE
Jar file

### ISSUE THREAD

**Issue by alexbagirov** [sankha93/codejudge#37]
Hello!

Can you provide ready jar file which can be used?

**Comment by CruiseDevice** [comment]
Were you able to figure out how to run "java -jar codejudge-compiler.jar". I am executing this command but getting this error "Error: Unable to access jarfile codejudge-compiler.jar"

**Comment by sankha93** [comment]
I just uploaded a binary of the built jar file here: https://github.com/sankha93/codejudge/releases/download/v1/codejudge-compiler.jar
